# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev3+g36f20f2.d20230304'
__version_tuple__ = version_tuple = (0, 1, 'dev3', 'g36f20f2.d20230304')
